[package]
name = "rust-chain-blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.7"
uuid = { version = "1.11.0", features = ["v4"] }
serde = "1.0.216"
rand = "0.8.5"
sha256 = "1.5.0"
rsa = { version = "0.9.7", features = ["pem"] }
